name: 📚 Ebooxly Auto-Update

on:
  schedule:
    # Exécution à 11h UTC (12h Maroc) et 23h UTC (00h Maroc)
 #   - cron: '0 11,23 * * *'
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Récupération du code
        uses: actions/checkout@v3

      - name: 🐍 Installation Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: 📦 Installation des outils
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          npm install -g firebase-tools

      - name: 🚀 Lancement du Script Ebooxly
        run: python update_ebooxly.py

      - name: 🔥 Déploiement vers Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: firebase deploy --only hosting --token "$FIREBASE_TOKEN"
